version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/CompeTournament.Backend"
      - "/CompeTournament.Shared"
      - "/CompeTournament.Mobile"
      - "/CompeTournament.Mobile.Core"
      - "/CompeTournament.Tests"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
