#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AzureMessagingSampleAndroid.Resource", IsApplication=true)]

namespace AzureMessagingSampleAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int buttonSize = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int circleCrop = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int colorScheme = 2130771969;
			
			// aapt resource value: 0x7f010004
			public const int imageAspectRatio = 2130771972;
			
			// aapt resource value: 0x7f010003
			public const int imageAspectRatioAdjust = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int scopeUris = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040008
			public const int common_action_bar_splitter = 2130968584;
			
			// aapt resource value: 0x7f040011
			public const int common_google_signin_btn_text_dark = 2130968593;
			
			// aapt resource value: 0x7f040009
			public const int common_google_signin_btn_text_dark_default = 2130968585;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_signin_btn_text_dark_disabled = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_signin_btn_text_dark_focused = 2130968588;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_signin_btn_text_dark_pressed = 2130968586;
			
			// aapt resource value: 0x7f040012
			public const int common_google_signin_btn_text_light = 2130968594;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_signin_btn_text_light_default = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_signin_btn_text_light_disabled = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int common_google_signin_btn_text_light_focused = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_signin_btn_text_light_pressed = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int common_plus_signin_btn_text_dark = 2130968595;
			
			// aapt resource value: 0x7f040000
			public const int common_plus_signin_btn_text_dark_default = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int common_plus_signin_btn_text_dark_disabled = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int common_plus_signin_btn_text_dark_focused = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int common_plus_signin_btn_text_dark_pressed = 2130968577;
			
			// aapt resource value: 0x7f040014
			public const int common_plus_signin_btn_text_light = 2130968596;
			
			// aapt resource value: 0x7f040004
			public const int common_plus_signin_btn_text_light_default = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int common_plus_signin_btn_text_light_disabled = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int common_plus_signin_btn_text_light_focused = 2130968583;
			
			// aapt resource value: 0x7f040005
			public const int common_plus_signin_btn_text_light_pressed = 2130968581;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_ic_googleplayservices = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_plus_signin_btn_icon_dark = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_plus_signin_btn_icon_dark_disabled = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_plus_signin_btn_icon_dark_focused = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_plus_signin_btn_icon_dark_normal = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_plus_signin_btn_icon_dark_pressed = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int common_plus_signin_btn_icon_light = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int common_plus_signin_btn_icon_light_disabled = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int common_plus_signin_btn_icon_light_focused = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int common_plus_signin_btn_icon_light_normal = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int common_plus_signin_btn_icon_light_pressed = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int common_plus_signin_btn_text_dark = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int common_plus_signin_btn_text_dark_disabled = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int common_plus_signin_btn_text_dark_focused = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int common_plus_signin_btn_text_dark_normal = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int common_plus_signin_btn_text_dark_pressed = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int common_plus_signin_btn_text_light = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int common_plus_signin_btn_text_light_disabled = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int common_plus_signin_btn_text_light_focused = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int common_plus_signin_btn_text_light_normal = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int common_plus_signin_btn_text_light_pressed = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_launcher = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int Icon = 2130837547;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070006
			public const int adjust_height = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int adjust_width = 2131165191;
			
			// aapt resource value: 0x7f070003
			public const int auto = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int dark = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int icon_only = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int light = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int none = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int standard = 2131165185;
			
			// aapt resource value: 0x7f070009
			public const int textViewMsg = 2131165193;
			
			// aapt resource value: 0x7f070002
			public const int wide = 2131165186;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05001f
			public const int app_name = 2131034143;
			
			// aapt resource value: 0x7f05001d
			public const int auth_google_play_services_client_facebook_display_name = 2131034141;
			
			// aapt resource value: 0x7f05001c
			public const int auth_google_play_services_client_google_display_name = 2131034140;
			
			// aapt resource value: 0x7f050015
			public const int common_google_play_services_api_unavailable_text = 2131034133;
			
			// aapt resource value: 0x7f050007
			public const int common_google_play_services_enable_button = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int common_google_play_services_enable_text = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int common_google_play_services_enable_title = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int common_google_play_services_install_button = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int common_google_play_services_install_text_phone = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_play_services_install_text_tablet = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_google_play_services_install_title = 2131034113;
			
			// aapt resource value: 0x7f050010
			public const int common_google_play_services_invalid_account_text = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int common_google_play_services_invalid_account_title = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int common_google_play_services_network_error_text = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int common_google_play_services_network_error_title = 2131034125;
			
			// aapt resource value: 0x7f050000
			public const int common_google_play_services_notification_ticker = 2131034112;
			
			// aapt resource value: 0x7f050019
			public const int common_google_play_services_restricted_profile_text = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int common_google_play_services_restricted_profile_title = 2131034136;
			
			// aapt resource value: 0x7f050017
			public const int common_google_play_services_sign_in_failed_text = 2131034135;
			
			// aapt resource value: 0x7f050016
			public const int common_google_play_services_sign_in_failed_title = 2131034134;
			
			// aapt resource value: 0x7f05001e
			public const int common_google_play_services_unknown_issue = 2131034142;
			
			// aapt resource value: 0x7f050012
			public const int common_google_play_services_unsupported_text = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int common_google_play_services_unsupported_title = 2131034129;
			
			// aapt resource value: 0x7f050013
			public const int common_google_play_services_update_button = 2131034131;
			
			// aapt resource value: 0x7f050009
			public const int common_google_play_services_update_text = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int common_google_play_services_update_title = 2131034120;
			
			// aapt resource value: 0x7f05000c
			public const int common_google_play_services_updating_text = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int common_google_play_services_updating_title = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int common_google_play_services_wear_update_text = 2131034122;
			
			// aapt resource value: 0x7f050014
			public const int common_open_on_phone = 2131034132;
			
			// aapt resource value: 0x7f05001a
			public const int common_signin_button_text = 2131034138;
			
			// aapt resource value: 0x7f05001b
			public const int common_signin_button_text_long = 2131034139;
			
			// aapt resource value: 0x7f050020
			public const int hello = 2131034144;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
